import { apiSuccess } from '@/lib/api-helpers';
import { withRateLimit } from '@/lib/api-rate-limit';

const schema = {
  version: '2026-02-27',
  tables: {
    plant_entities: {
      primary_key: 'id',
      description: 'Species-level records and taxonomy anchors.',
      columns: [
        'id',
        'slug',
        'canonical_name',
        'botanical_name',
        'family',
        'genus',
        'species',
        'entity_type',
        'curation_status',
        'display_category',
        'taxonomy_node_id',
      ],
      relations: {
        cultivars: { table: 'cultivars', foreign_key: 'plant_entity_id', cardinality: 'one_to_many' },
        growing_profile: {
          table: 'species_growing_profiles',
          foreign_key: 'plant_entity_id',
          cardinality: 'one_to_one',
        },
      },
    },
    cultivars: {
      primary_key: 'id',
      description: 'Named cultivars and breeding lines.',
      columns: [
        'id',
        'slug',
        'canonical_name',
        'plant_entity_id',
        'material_type',
        'breeder',
        'origin_location',
        'year_released',
        'patent_status',
        'curation_status',
      ],
      relations: {
        plant_entity: { table: 'plant_entities', foreign_key: 'plant_entity_id', cardinality: 'many_to_one' },
        offers: { table: 'inventory_offers', foreign_key: 'cultivar_id', cardinality: 'one_to_many' },
      },
    },
    inventory_offers: {
      primary_key: 'id',
      description: 'Nursery inventory snapshot rows from pipeline runs.',
      columns: [
        'id',
        'nursery_id',
        'cultivar_id',
        'plant_entity_id',
        'raw_product_name',
        'offer_status',
        'raw_price_text',
        'price_cents',
        'raw_availability',
        'product_page_url',
      ],
      relations: {
        nursery: { table: 'nurseries', foreign_key: 'nursery_id', cardinality: 'many_to_one' },
        cultivar: { table: 'cultivars', foreign_key: 'cultivar_id', cardinality: 'many_to_one' },
        plant_entity: { table: 'plant_entities', foreign_key: 'plant_entity_id', cardinality: 'many_to_one' },
      },
    },
    nurseries: {
      primary_key: 'id',
      description: 'Nursery metadata and consent/tracking attributes.',
      columns: [
        'id',
        'slug',
        'name',
        'website_url',
        'location_city',
        'location_state',
        'location_country',
        'latitude',
        'longitude',
        'is_active',
        'curation_status',
      ],
    },
    species_growing_profiles: {
      primary_key: 'plant_entity_id',
      description: 'One profile per species for climate and horticultural traits.',
      columns: [
        'plant_entity_id',
        'usda_zone_min',
        'usda_zone_max',
        'chill_hours_min',
        'chill_hours_max',
        'soil_ph_min',
        'soil_ph_max',
        'soil_drainage',
        'sun_requirement',
        'growth_rate',
        'mature_height_min_ft',
        'mature_height_max_ft',
      ],
    },
    community_listings: {
      primary_key: 'id',
      description: 'Anonymous WTS/WTB listings pending admin moderation.',
      columns: [
        'id',
        'listing_type',
        'raw_cultivar_text',
        'raw_species_text',
        'material_type',
        'quantity',
        'price_cents',
        'location_state',
        'status',
        'trust_tier',
        'resolve_confidence',
        'cultivar_id',
        'plant_entity_id',
        'created_at',
        'expires_at',
      ],
    },
    material_search_index: {
      type: 'materialized_view',
      description: 'Search index for plant entities and cultivars.',
      columns: [
        'entity_id',
        'index_source',
        'slug',
        'species_slug',
        'canonical_name',
        'botanical_name',
        'species_common_name',
        'material_type',
        'genus',
        'family',
        'search_text',
        'active_offer_count',
      ],
    },
  },
  enums: {
    entity_type: ['species', 'subspecies', 'hybrid_species', 'species_group'],
    curation_status: ['draft', 'reviewed', 'published'],
    material_type: [
      'cultivar_clone',
      'named_seed_strain',
      'breeding_population',
      'geographic_population',
      'species_seedling',
      'unknown_named_line',
    ],
    offer_status: ['active', 'stale', 'sold_out', 'discontinued'],
    listing_status: ['pending', 'approved', 'rejected', 'expired'],
    listing_type: ['wts', 'wtb'],
  },
} as const;

export const GET = withRateLimit(async function GET(request: Request) {
  return apiSuccess(schema, undefined, { self: '/api/schema' });
}, { max: 30 });
